### ISSUE TITLE
Bug with define if value is right

### ISSUE THREAD

**Issue by MilitaryNekoMaid** [pushkart2/slidergame#1]
Is this bug only for me or others too?

i want to do something like this:

`local data = exports["slidergame"]:slider()
if data[1] == 5 then
print(data[1])
end`
it's not printing so i tried to print data before like that
`local data = exports["slidergame"]:slider()
print(data[1])
if data[1] == 5 then
print(data[1])
end`
the first print prints 5 but second does not work

**Comment by pushkart2** [comment]
Its a string, convert it to number using tonumber(data[1])
